---
title: "Kickstarter Campaign Visualization"
author: "by Gabriel Erichson"
output: 
  html_document:
    df_print: paged
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: 
        collapsed: true
    number_sections: true
    theme: sandstone
    highlight: haddock
    css: style.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  result="hide",
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  comment = "#>"
)

options(scipen = 9999999)
library(lubridate)
library(scales)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(paletti)


# WARNA
mycolor = c(
  dark_blue="#003f5c", 
  light_blue="#2f4b7c", 
  light_purple ="#665191",
  dark_pink="#a05195", 
  light_pink="#d45087", 
  light_red="#f95d6a", 
  dark_orange="#ff6347",
  light_orange="#ff7c43",
  semi_orange="#e79658",
  orange="#dda15a",
  cream="#b59378",
  dark_cream="#A57F5F",
  choc="#85664B",
  dark_choc="#6b5340"
)

mycolorfill = c(
  
  light_blue="#2f4b7c", 
  light_purple ="#665191",
  dark_pink="#a05195", 
  light_pink="#d45087", 
  light_red="#f95d6a", 
  dark_orange="#ff6347",
  
  semi_orange="#e79658",
  orange="#dda15a",
  cream="#b59378",
  dark_cream="#A57F5F",
  choc="#85664B",
  dark_choc="#6b5340",
  light_orange="#ff7c43"
)


viz_palette(mycolor)
mycolor_fill  <- get_scale_fill(get_pal(mycolorfill))
mycolor_color <- get_scale_color(get_pal(mycolor))
mycolor_hex <- get_hex(mycolor)

```


<br/>
**ABSTRACT** <br/>
Kickstarter adalah sebuah platform yang memberikan ruang pendanaan untuk proyek kreatif secara crowdfunding. Informasi lengkap tentang kickstarter bisa mengunjungi web https://www.kickstarter.com/ . Tujuan dari proyek ini adalah untuk memprediksi jumlah pembiayaan yang didapatkan sebuah proyek dan keberhasilan atau kegagalan kampanye Kickstarter saat diluncurkan.<br/><br/>

**INTRODUCTION**<br/>
`Crowdfunding` adalah praktik mendanai proyek, usaha atau lainnya dengan meningkatkan kontribusi moneter dari banyak orang. Saat ini banyak proses crowdfunding terjadi secara online melalui berbagai situs web dan salah satunya adalah Kickstarter. Aspek yang paling penting tentang meluncurkan proyek di Kickstarter adalah bahwa jika proyek gagal memenuhi tujuan pendanaan minimumnya, maka proyek tidak akan menerima dana apa pun. Proyek Kickstarter yang dianalisis kali ini termasuk dalam salah satu dari 14 kategori (Art, Comics, Dance, Design, Fashion, Film & Video, Film & amp; Video, Food, Games, Music, Photography, Publishing, Technology, Theater dan 51 subkategori.<br/><br/>

**PRELIMINARY ANALYSIS**<br/>
Dataset untuk proyek ini diambil dari repositori `webroboto.io`. Mereka mengembangkan scrapper robot yang mengambil semua data proyek Kickstarter secara bulanan semenjak 2009. Ada kemungkinan data proyek tidak lengkap atau terjadi duplikasi dalam dataset karena perubahan dalam pendekatan pengumpulan data oleh webroboto.io. Hal ini disampaikan oleh pihak `webroboto.io` pada situs web https://webrobots.io/kickstarter-datasets/ . Dataset yang dianalisis mulai dari 2009-2019 dengan jumlah data raw sebanyak 211.076 observasi. Setiap proyek kicstarter memiliki status `failed`, `successful`, `live`, `suspended` atau `canceled`. Dalam analisis ini, saya hanya tertarik pada proyek kicktarter yang sukses atau gagal, sehingga saya memutuskan untuk membuang data observasi dengan status lainnya. Selain itu, saya juga membuang data proyek kickstarter yang memiliki Missing Value karena dapat mempengaruhi proses pemodelan. Sehingga dataset yang digunakan untuk analisis dan pemodelan ini memiliki 164,970 observasi dan 14 variabel.<br/><br/>
